name: build-and-push

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      run: |
        cd OracleDatabase/SingleInstance/dockerfiles
        ./buildDockerImage.sh -v 18.4.0 -x -o -t jlundy/oracle-db:18.4.0-xe
        docker login -u ${{ secrets.DOCKERHUB_USERNAME}} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push jlundy/oracle-db:18.4.0-xe
